export const GET_FEED = 'GET_FEED';
export const LIKE_UNLIKE_FEED = 'LIKE_UNLIKE_FEED';
export const CREATE_COMMENT_FEED = 'CREATE_COMMENT_FEED';
export const DELETE_COMMENT_FROM_FEED = 'DELETE_COMMENT_FROM_FEED';
export const SHOW_COMMENTS_FEED = 'SHOW_COMMENTS_FEED';
